---
- group:
    name: "{{ username }}"
    state: present
    gid: 3133000

- user:
    name: "{{ username }}"
    state: present
    group: users
    groups: "{{ username }},sudo,staff"
    uid: 3133700
    shell: /usr/bin/fish

- authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items:
  - ed25519.pub
  - rsa.pub

- template:
    src: sudo.conf.j2
    dest: "/etc/sudoers.d/{{ username }}"
