---
- apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
  - htop
  - unzip
  - zip
  - zsh
  - build-essential
  - imagemagick
- file:
    path: "/home/{{ username }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
